name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  issues: write

jobs:
  test:
    name: Pruebas en Node.js
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: usar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache de dependencias
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instalar dependencias
        run: npm install

  build:
    name: Simular Build
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
      
      - name: Instalar dependencias
        run: npm install

      - name: Simular build
        run: |
          mkdir build
          cp -r src/ build/src/
          echo "Build generado automÃ¡ticamente" > build/info.txt

      - name: Guardar artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: build/

  notificar-exito:
    if: success()
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Crear issue por CI exitoso
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "CI completado correctamente"
          content-filepath: .github/success-message.md
          labels: success, ci

  notifcar-error:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Crear un issue por error el fallo en CI
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Fallo en CI"
          content-filepath: .github/failure-message.md
          labels: bug, ci